import * as yup from 'yup';
export const schemaData = {
    'Analyzers' : {
        name: yup.string().required('required'),
        vendor: yup.string().required('required'),
        desc: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'AnalyzerParameters' : {
        analyzerId: yup.number().required('required'),
        liscodeId: yup.number().required('required'),
        lascodeId: yup.number().required('required'),
        // isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Cpts' : {
        name: yup.string().required('required'),
        description: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'LisCodes' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestParameters' : {
        cptid: yup.number().required('required'),
        liscodeId: yup.number().required('required'),
        unit: yup.string().required('required'),
        range: yup.string().required('required'),
        // isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'GenLookups' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    // ==================
    'InvoiceDetails' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'InvoiceMasters' : {
        keyName: yup.string().required('required'),
        value: yup.string().required('required'),
        type: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'OrderDetails' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'OrderMasters' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyPendingQueues' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyResultDetails' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'PathologyResultMasters' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'RoleModules' : {
        roleId: yup.string().required('required'),
        moduleId: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Modules' : {
        roleId: yup.string().required('required'),
        moduleId: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Roles' : {
        name: yup.string().required('required'),
        type: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestCategories' : {
        categoryName: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestSamples' : {
        cptid: yup.string().required('required'),
        sampleName: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestUnits' : {
        name: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Users' : {
        name: yup.string().required('required'),
        mobile: yup.string().required('required'),
        email: yup.string().required('required'),
        username: yup.string().required('required'),
        password: yup.string().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
}