import * as yup from 'yup';
export const schemaData = {
    'Analyzers' : {
        name: yup.string().required('required'),
        vendor: yup.string().required('required'),
        isActive: yup.boolean().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'AnalyzerParameter' : {
        analyzerId: yup.number().required('required'),
        liscodeId: yup.number().required('required'),
        lascodeId: yup.number().required('required'),
        isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'Cpts' : {
        name: yup.string().required('required'),
        isActive: yup.boolean().required('required'),
        description: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'LisCodes' : {
        name: yup.string().required('required'),
        type: yup.string().required('required'),
        isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
    'TestParameters' : {
        cptid: yup.number().required('required'),
        liscodeId: yup.number().required('required'),
        unit: yup.string().required('required'),
        range: yup.string().required('required'),
        isActive: yup.boolean().required('required'),
        desc: yup.string().required('required'),
        // createdOn: yup.string().required('required'),
        // updatedOn: yup.string().required('required'),
        // createdBy: yup.string().required('required'),
        // updatedBy: yup.string().required('required'),
    },
}